# Generated by Django 3.2.6 on 2023-09-25 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField(default=0)),
                ('descripcion', models.CharField(max_length=200)),
                ('fabricante', models.CharField(max_length=50)),
                ('concentracion', models.IntegerField()),
                ('administracion', models.CharField(max_length=50)),
                ('medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.medico')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField(default=0)),
                ('descripcion', models.CharField(max_length=200)),
                ('proposito', models.CharField(max_length=50)),
                ('unidad', models.CharField(max_length=50)),
                ('medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.medico')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField(default=0)),
                ('descripcion', models.CharField(max_length=200)),
                ('funcion', models.CharField(max_length=50)),
                ('medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.medico')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
