# Generated by Django 3.2.6 on 2023-10-10 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0003_eps_correo'),
        ('usuario', '0002_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='paciente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='usuario.paciente'),
            preserve_default=False,
        ),
    ]
