# Generated by Django 3.2.6 on 2023-11-06 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0003_administrador'),
        ('administrativo', '0004_factura_paciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('completada', models.BooleanField()),
                ('factura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrativo.factura')),
                ('medicoCita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.paciente')),
            ],
        ),
    ]
