# Generated by Django 3.2.6 on 2023-09-25 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enfermera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('clave', models.CharField(max_length=50)),
                ('identificacion', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Farmaceutico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('clave', models.CharField(max_length=50)),
                ('identificacion', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('clave', models.CharField(max_length=50)),
                ('identificacion', models.CharField(max_length=50)),
                ('especialidad', models.CharField(max_length=50)),
                ('licencia', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
