# Generated by Django 3.2.6 on 2023-10-10 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0003_eps_correo'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('clave', models.CharField(max_length=50)),
                ('identificacion', models.CharField(max_length=50)),
                ('numeroDeSeguro', models.CharField(max_length=50)),
                ('eps', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrativo.eps')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
