# Generated by Django 3.2.6 on 2023-11-05 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_paciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('clave', models.CharField(max_length=50)),
                ('identificacion', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
